object Version {
    const val kotlin                       = "1.7.10"
    const val firebaseBom                  = "27.1.0"
    const val appCompat                    = "1.4.1"
    const val core                         = "1.7.0"
    const val coroutine                    = "1.3.9"
    const val lifecycle                    = "2.4.0"
    const val retrofit                     = "2.9.0"
    const val okHttp                       = "4.9.3"
    const val gson                         = "2.8.6"
    const val retrofitGson                 = "2.8.0"
    const val retrofitScalar               = "2.1.0"
    const val nav                          = "2.5.2"
    const val materialUi                   = "1.3.0-alpha01"
    const val viewPager                    = "1.1.0-alpha01"
    const val cardView                     = "1.0.0"
    const val constraintLayout             = "2.0.1"
    const val glide                        = "4.11.0"
    const val permission                   = "3.0.0"
    const val khronos                      = "0.9.0"
    const val loggingInterceptor           = "3.10.0"
    const val hilt                         = "2.42"
    const val fragmentKtx                  = "1.2.4"
    const val swipeToRefresh               = "1.0.0"
    const val room                         = "2.2.5"
    const val lingver                      = "1.3.0"
    const val multidex                     = "2.0.1"
    const val userAgentInterceptor         = "1.0.1"
    const val jcropImageView               = "0.22"
    const val legacySupportV4              = "1.0.0"
    const val dynatrace_standalone_version = "8.217.1.1003"
    const val googleTagManager             = "17.0.0"
    const val playCore                     = "1.8.3"
    const val playCoreCtx                  = "1.8.1"
    const val bytes                        = "1.4.0"
    const val facebook                     = "8.1.0"
    const val chucker                      = "3.5.2"
    const val tooLargeTool                 = "0.3.0@aar"
    const val cameraCore                   = "1.1.0-alpha04"
    const val camera2                      = "1.1.0-alpha04"
    const val cameraLifecycle              = "1.1.0-alpha04"
    const val cameraView                   = "1.0.0-alpha24"
    const val mlkitTextRecognition         = "16.1.3"
    const val barcodeScanning              = "16.1.1"
    const val draggableView                = "1.0.0"
    const val picasso                      = "2.71828"

    object Test {
        const val jUnitVersion = "5.9.0"
        const val mockitoCoreVersion = "2.23.0"
        const val coroutineTestVersion = "1.3.1"
        const val mockitoKotlinVersion = "2.2.0"
        const val coreTestingVersion = "1.4.0"
        const val androidJUnitVersion = "1.1.3"
        const val androidEspressoVersion = "3.2.0"
        const val androidArchVersion = "2.1.0"
    }
}